apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: %%%KOPS_CA_DATA%%%
    server: https://api.%%%KOPS_CLUSTER_NAME%%%
  name: %%%KOPS_CLUSTER_NAME%%%
contexts:
- context:
    cluster: %%%KOPS_CLUSTER_NAME%%%
    user: %%%KOPS_CLUSTER_NAME%%%.exec
  name: %%%KOPS_CLUSTER_NAME%%%
current-context: %%%KOPS_CLUSTER_NAME%%%
kind: Config
preferences: {}
users:
- name: %%%KOPS_CLUSTER_NAME%%%.exec
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - %%%KOPS_CLUSTER_NAME%%%
      - -r
      - arn:aws:iam::%%%ACCOUNT_ID%%%:role/%%%KOPS_OPERATION_ROLE%%%
      command: heptio-authenticator-aws
      env: null